full_name = "kate austen"
print(full_name[0])
print(full_name[1])
print(full_name[2])
print(full_name[-1])
print(full_name[-2])
print(full_name[-11])
print(full_name[::-1])
print(len(full_name))
# IndexError: print(full_name[11])
# IndexError: print(full_name[-12])